### PR TITLE
Fix ingress hosts, allow node tolerations/affinity

### PR DESCRIPTION
**Pull request by bjw-s**
When trying to run the Helm chart for myself I ran in to some issues with my setup. Mainly the multiple hosts on the Ingress was not working for me due to an exception. This PR addresses that.

Secondly, the Deployment did not take into account any Tolerations or Node Affinity if specified in the values. This PR should fix that.

Lastly I've taken the liberty to rename some variables and relocate dependencies to be more in accordance with Helm best practices.

### CODE REVIEW

**Comment by ozonep** [comment]
Not all names are updated!
In gitea deployment you still use "fullname" template, even though it's not defined in _helpers anymore.
Line 38 :)

**Comment by bjw-s** [comment]
> Not all names are updated!
> In gitea deployment you still use "fullname" template, even though it's not defined in _helpers anymore.
> Line 38 :)

I noticed that as well when I was deploying to my staging environment, I've pushed that change as well 😄

**Comment by cdrage** [comment]
Hi @Juggels unfortunately you'll have to rebase as I just merged in: https://github.com/k8s-land/gitea-chart/pull/13

Do you mind going through / rebasing and testing it out? Sorry! But needed to merge in https://github.com/k8s-land/gitea-chart/pull/13 for secrets.

**Comment by bjw-s** [comment]
No problem, will do that later tonight :)

**Comment by bjw-s** [comment]
I found some time in between things, and performed the rebase. 
I did just realise that one of my commits could be potentially "breaking" in the sense that I changed the way images can be specified to be more compatible with [HelmOperator](https://docs.fluxcd.io/en/stable/references/helm-operator-integration/). That should possibly mean a different chart version bump

**Comment by cdrage** [comment]
> I found some time in between things, and performed the rebase.
> I did just realise that one of my commits could be potentially "breaking" in the sense that I changed the way images can be specified to be more compatible with [HelmOperator](https://docs.fluxcd.io/en/stable/references/helm-operator-integration/). That should possibly mean a different chart version bump

Not a problem! We can release a new version. I like that you've included MariaDB.

**Comment by bjw-s** [comment]
I’ll try to see if I can make the Bitnami `memcached` chart a similar dependency instead of a container within this deployment. Would you be open to that? I'll create a separate branch PR for that one, as it's quite a fundamental change.

**Pull request closed without merging**
